import enum

class DomainCategory(str, enum.Enum):
    TECH = "TECH"
    LAW = "LAW"
    HR = "HR"
    FINANCE = "FINANCE"
    SALES_MARKETING = "SALES_MARKETING"
    OPERATIONS_ADMIN = "OPERATIONS_ADMIN"
    HEALTHCARE = "HEALTHCARE"
    ENGINEERING_MANUFACTURING = "ENGINEERING_MANUFACTURING"
    EDUCATION = "EDUCATION"
    DESIGN_PRODUCT = "DESIGN_PRODUCT"
    OTHER = "OTHER"
