"""add_source_timestamps_indexes

Revision ID: 141336497dbb
Revises: 4a1406f09555
Create Date: 2026-06-24 12:36:38.293802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141336497dbb'
down_revision: Union[str, Sequence[str], None] = '4a1406f09555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interviewing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.add_column('candidates', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_match_results_job_id'), 'match_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_results_match_percentage'), 'match_results', ['match_percentage'], unique=False)
    op.create_index(op.f('ix_recruitment_events_created_at'), 'recruitment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_recruitment_events_event_type'), 'recruitment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_resumes_parsing_status'), 'resumes', ['parsing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_parsing_status'), table_name='resumes')
    op.drop_index(op.f('ix_recruitment_events_event_type'), table_name='recruitment_events')
    op.drop_index(op.f('ix_recruitment_events_created_at'), table_name='recruitment_events')
    op.drop_index(op.f('ix_match_results_match_percentage'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_job_id'), table_name='match_results')
    op.drop_column('candidates', 'source')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_column('applications', 'rejected_at')
    op.drop_column('applications', 'offered_at')
    op.drop_column('applications', 'interviewing_at')
    op.drop_column('applications', 'shortlisted_at')
    # ### end Alembic commands ###
