"""Add assistant tables

Revision ID: 4a1406f09555
Revises: db31c1ad142e
Create Date: 2026-06-24 12:19:03.442741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1406f09555'
down_revision: Union[str, Sequence[str], None] = 'db31c1ad142e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_interview_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('generated_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_interview_questions_id'), 'generated_interview_questions', ['id'], unique=False)
    op.create_table('generated_job_descriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('generated_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_job_descriptions_id'), 'generated_job_descriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_job_descriptions_id'), table_name='generated_job_descriptions')
    op.drop_table('generated_job_descriptions')
    op.drop_index(op.f('ix_generated_interview_questions_id'), table_name='generated_interview_questions')
    op.drop_table('generated_interview_questions')
    # ### end Alembic commands ###
