"""Add resume_id to recruitment_events

Revision ID: 5cef53b66d93
Revises: cff87aa0286d
Create Date: 2026-06-23 16:13:16.466805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cef53b66d93'
down_revision: Union[str, Sequence[str], None] = 'cff87aa0286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_recruitment_events_resume', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitment_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recruitment_events_resume', type_='foreignkey')
        batch_op.drop_column('resume_id')
    # ### end Alembic commands ###
