"""add_domain_to_job

Revision ID: aa84752e1a4a
Revises: d5dc69a3e866
Create Date: 2026-07-05 14:37:49.027124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa84752e1a4a'
down_revision: Union[str, Sequence[str], None] = 'd5dc69a3e866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('jobs', sa.Column('domain', sa.String(), server_default='OTHER', nullable=False))
    op.create_index(op.f('ix_jobs_domain'), 'jobs', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_domain'), table_name='jobs')
    op.drop_column('jobs', 'domain')

    # ### end Alembic commands ###
