"""Add failure reason and experience years

Revision ID: cff87aa0286d
Revises: 72361bb678b4
Create Date: 2026-06-23 16:05:24.190700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff87aa0286d'
down_revision: Union[str, Sequence[str], None] = '72361bb678b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_resume_data', sa.Column('total_experience_years', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'failure_reason')
    op.drop_column('parsed_resume_data', 'total_experience_years')
    # ### end Alembic commands ###
