"""Add candidate fields and indexes

Revision ID: d5dc69a3e866
Revises: eb3052655b8a
Create Date: 2026-07-04 18:13:23.602962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5dc69a3e866'
down_revision: Union[str, Sequence[str], None] = 'eb3052655b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('candidates', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('notice_period', sa.String(), nullable=True))
    op.create_index(op.f('ix_candidates_current_location'), 'candidates', ['current_location'], unique=False)
    op.create_index(op.f('ix_candidates_domain'), 'candidates', ['domain'], unique=False)
    op.create_index(op.f('ix_candidates_total_experience_years'), 'candidates', ['total_experience_years'], unique=False)
    op.create_index(op.f('ix_jobs_department'), 'jobs', ['department'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_department'), table_name='jobs')
    op.drop_index(op.f('ix_candidates_total_experience_years'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_domain'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_current_location'), table_name='candidates')
    op.drop_column('candidates', 'notice_period')
    op.drop_column('candidates', 'education_level')
    op.drop_column('candidates', 'domain')
    # ### end Alembic commands ###
