"""Make job fields optional

Revision ID: eb3052655b8a
Revises: 141336497dbb
Create Date: 2026-06-26 15:58:04.916643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb3052655b8a'
down_revision: Union[str, Sequence[str], None] = '141336497dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
