export const DOMAIN_CATEGORIES = [
  'TECH',
  'LAW',
  'HR',
  'FINANCE',
  'SALES_MARKETING',
  'OPERATIONS_ADMIN',
  'HEALTHCARE',
  'ENGINEERING_MANUFACTURING',
  'EDUCATION',
  'DESIGN_PRODUCT',
  'OTHER'
];
